<a href="https://colab.research.google.com/github/shamabansal17/Startups_funding_Analysis/blob/main/funding_startup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

We have a set of project ideas for you to choose from and work around for the last block of Domain Analytics. You have to work on the datasets to drive insights and recommendations out of them. Imagine you're presenting to the top executives of a company â€“ your goal is to convey insights in a compelling manner, supported by solid data. Choose any 1 of the 2 projects that spark your interest, and let's embark on this journey of turning data into actionable recommendations for the benefit of upper management.

1. Funding in startups
Funding a startup with a revolutionary idea may seem very attractive, but having insights and knowledge about the condition of startups founded in the past can help in shaping future startup ideas and positioning it well in today's markets, which can ultimately lead to increasing its performance many folds, in the real world.
Data: https://drive.google.com/drive/folders/1aIFo7dBFEPlpXWq6brCFUOgXZSLkq1tw?usp=sharing
Uncover trends and insights that guide strategic decision-making. Consider analyzing the distribution of funding across different categories, markets, and regions to identify sectors with higher investment potential.
Explore the correlation between a startup's funding characteristics and its funding success, examining factors such as the funding rounds, funding types, and geographical locations. Additionally, assess the impact of economic factors on funding, and propose strategies for startups to optimize their funding journeys. This project has the potential to offer valuable insights for both aspiring entrepreneurs and investors in the dynamic landscape of startup financing.
That does not limit the project but serves as a starter and keeps it open to let you explore more, go into as much depth as you can, and make it your project. The extra research/insights/recommendations you incorporate into your study, beyond the provided topics are important.

# Funding in startups
Funding a startup with a revolutionary idea may seem very attractive, but having insights and knowledge about the condition of startups founded in the past can help in shaping future startup ideas and positioning it well in today's markets, which can ultimately lead to increasing its performance many folds, in the real world.

Uncover trends and insights that guide strategic decision-making. Consider analyzing the distribution of funding across different categories, markets, and regions to identify sectors with higher investment potential.
Explore the correlation between a startup's funding characteristics and its funding success, examining factors such as the funding rounds, funding types, and geographical locations. Additionally, assess the impact of economic factors on funding, and propose strategies for startups to optimize their funding journeys. This project has the potential to offer valuable insights for both aspiring entrepreneurs and investors in the dynamic landscape of startup financing.

# Startup Funding Analysis

## Project Overview

This project aims to uncover trends and insights that guide strategic decision-making in the startup ecosystem. By analyzing the distribution of funding across different categories, markets, and regions, the project identifies sectors with higher investment potential. It also explores the correlation between a startup's funding characteristics and its success, examining factors such as funding rounds, funding types, and geographical locations. Additionally, the project assesses the impact of economic factors on funding and proposes strategies for startups to optimize their funding journeys.

## Objectives

1. **Distribution Analysis**:
   - Analyze the distribution of startup funding across various categories, such as industry sectors, markets, and geographical regions.
   - Identify sectors with higher investment potential.

2. **Correlation Analysis**:
   - Explore the relationship between funding characteristics (e.g., funding rounds, types of investors, and location) and the success of startups.
   - Investigate the impact of geographical location on funding opportunities.

3. **Strategic Recommendations**:
   - Propose strategies for startups to optimize their funding journeys based on insights from the analysis.
   - Provide actionable recommendations for aspiring entrepreneurs and investors.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
! gdown 110tJaSocsCTvgqjJ3LyfzZOmhy8woTfP

Downloading...
From: https://drive.google.com/uc?id=110tJaSocsCTvgqjJ3LyfzZOmhy8woTfP
To: /content/investments_VC.csv
100% 12.5M/12.5M [00:00<00:00, 96.7MB/s]

In [3]:
import chardet

with open('investments_VC.csv', 'rb') as f:
    result = chardet.detect(f.read(10000))          # 10000 will read 1 mb data only to speed up , it should be use for bigger datasets

print(result['encoding'])

MacRoman

In [34]:
df=pd.read_csv('investments_VC.csv',encoding='latin')
df.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,undisclosed,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,News,"17,50,000",acquired,USA,NY,New York City,New York,1.0,2012-06-01,2012-06,2012-Q2,2012.0,2012-06-30,2012-06-30,1750000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"40,00,000",operating,USA,CA,Los Angeles,Los Angeles,2.0,NaN,NaN,NaN,NaN,2010-06-04,2010-09-23,0.0,4000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Publishing,"40,000",operating,EST,NaN,Tallinn,Tallinn,1.0,2012-10-26,2012-10,2012-Q4,2012.0,2012-08-09,2012-08-09,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Electronics,"15,00,000",operating,GBR,NaN,London,London,1.0,2011-04-01,2011-04,2011-Q2,2011.0,2011-04-01,2011-04-01,1500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/organization/r-ranch-and-mine,-R- Ranch and Mine,NaN,|Tourism|Entertainment|Games|,Tourism,"60,000",operating,USA,TX,Dallas,Fort Worth,2.0,2014-01-01,2014-01,2014-Q1,2014.0,2014-08-17,2014-09-26,0.0,0.0,60000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
! gdown 1oQX-4sum2y8cCRYdO3_qV928qaXemY5YR-da1h0lZf8

Downloading...
From (original): https://drive.google.com/uc?id=1oQX-4sum2y8cCRYdO3_qV928qaXemY5YR-da1h0lZf8
From (redirected): https://docs.google.com/document/d/1oQX-4sum2y8cCRYdO3_qV928qaXemY5YR-da1h0lZf8/export?format=docx
To: /content/Startup funding Data description.docx
8.95kB [00:00, 18.1MB/s]

In [36]:
! pip install python-docx

from docx import Document

# Load the .docx file
doc = Document('Startup funding Data description.docx')

Requirement already satisfied: python-docx in /usr/local/lib/python3.10/dist-packages (1.1.2)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from python-docx) (4.9.4)
Requirement already satisfied: typing-extensions>=4.9.0 in /usr/local/lib/python3.10/dist-packages (from python-docx) (4.12.2)

In [37]:
# Extract and format table data
for table in doc.tables:
    for i, row in enumerate(table.rows):
        row_data = [cell.text.strip() for cell in row.cells]
        if i == 0:
              print(f"{'Column Index':<15} {'Column Name':<20} {'Description':<50}")  # Table headers
              print("=" * 90)
        else:
              print(f"{row_data[0]:<15} {row_data[1]:<20} {row_data[2]:<50}")

Column Index    Column Name          Description
==========================================================================================
0               permalink            Static hyperlink for the startup on Crunchbase...
1               name                 name of the startup
2               homepage_url         Website address of the startup
3               category_list        in which category the startups fall
4               market               which market the startup caters to
5               funding_total_usd    total funding received(in USD)
6               status               current operating status
7               country_code         country of origin
8               state_code           state of origin
9               region               region
10              city                 city of origin
11              funding_rounds       total rounds of funding
12              founded_at           date of founding
13              founded_month        month of founding
14              founded_quarter      quarter of founding
15              founded_year         year of founding
16              first_funding_at     date of first funding
17              last_funding_at      date of last funding
18              seed                 seed funding received(in USD)
19              venture              venture funding received(in USD)
20              equity_crowdfunding  funding received by diluting equity
21              undisclosed          other undisclosed funding sources
22              convertible_note     funding received from convertible notes
23              debt_financing       funding received from debts
24              angel                funding received from angel investors
25              grant                funding from grants
26              private_equity       funding from private equity
27              post_ipo_equity      funding from equity dilution after IPO
28              post_ipo_debt        funding from debts after IPO
29              secondary_market     funding from secondary markets
30              product_crowdfunding funding from crowdfunding
31              round_A              round A funding
32              round_B              round B funding
33              round_C              round C funding
34              round_D              round D funding
35              round_E              round E funding
36              round_F              round F funding

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54294 entries, 0 to 54293
Data columns (total 39 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   permalink             49438 non-null  object
 1   name                  49437 non-null  object
 2   homepage_url          45989 non-null  object
 3   category_list         45477 non-null  object
 4    market               45470 non-null  object
 5    funding_total_usd    49438 non-null  object
 6   status                48124 non-null  object
 7   country_code          44165 non-null  object
 8   state_code            30161 non-null  object
 9   region                44165 non-null  object
 10  city                  43322 non-null  object
 11  funding_rounds        49438 non-null  float64
 12  founded_at            38554 non-null  object
 13  founded_month         38482 non-null  object
 14  founded_quarter       38482 non-null  object
 15  founded_year          38482 non-null  float64
 16  first_funding_at      49438 non-null  object
 17  last_funding_at       49438 non-null  object
 18  seed                  49438 non-null  float64
 19  venture               49438 non-null  float64
 20  equity_crowdfunding   49438 non-null  float64
 21  undisclosed           49438 non-null  float64
 22  convertible_note      49438 non-null  float64
 23  debt_financing        49438 non-null  float64
 24  angel                 49438 non-null  float64
 25  grant                 49438 non-null  float64
 26  private_equity        49438 non-null  float64
 27  post_ipo_equity       49438 non-null  float64
 28  post_ipo_debt         49438 non-null  float64
 29  secondary_market      49438 non-null  float64
 30  product_crowdfunding  49438 non-null  float64
 31  round_A               49438 non-null  float64
 32  round_B               49438 non-null  float64
 33  round_C               49438 non-null  float64
 34  round_D               49438 non-null  float64
 35  round_E               49438 non-null  float64
 36  round_F               49438 non-null  float64
 37  round_G               49438 non-null  float64
 38  round_H               49438 non-null  float64
dtypes: float64(23), object(16)
memory usage: 16.2+ MB

In [39]:
df.nunique()

permalink               49436
name                    49350
homepage_url            45850
category_list           16675
 market                   753
 funding_total_usd      14617
status                      3
country_code              115
state_code                 61
region                   1089
city                     4188
funding_rounds             17
founded_at               3369
founded_month             420
founded_quarter           218
founded_year              103
first_funding_at         3914
last_funding_at          3657
seed                     3337
venture                  9300
equity_crowdfunding       252
undisclosed               687
convertible_note          299
debt_financing           1872
angel                     999
grant                     532
private_equity            847
post_ipo_equity           239
post_ipo_debt              57
secondary_market           20
product_crowdfunding      176
round_A                  2035
round_B                  1269
round_C                   740
round_D                   458
round_E                   225
round_F                   110
round_G                    32
round_H                     5
dtype: int64

In [40]:
df.isna().sum()

permalink                4856
name                     4857
homepage_url             8305
category_list            8817
 market                  8824
 funding_total_usd       4856
status                   6170
country_code            10129
state_code              24133
region                  10129
city                    10972
funding_rounds           4856
founded_at              15740
founded_month           15812
founded_quarter         15812
founded_year            15812
first_funding_at         4856
last_funding_at          4856
seed                     4856
venture                  4856
equity_crowdfunding      4856
undisclosed              4856
convertible_note         4856
debt_financing           4856
angel                    4856
grant                    4856
private_equity           4856
post_ipo_equity          4856
post_ipo_debt            4856
secondary_market         4856
product_crowdfunding     4856
round_A                  4856
round_B                  4856
round_C                  4856
round_D                  4856
round_E                  4856
round_F                  4856
round_G                  4856
round_H                  4856
dtype: int64

In [41]:
df=df[~df.isna().all(axis=1)]
df.isna().sum()/len(df)*100

permalink                0.000000
name                     0.002023
homepage_url             6.976415
category_list            8.012056
 market                  8.026215
 funding_total_usd       0.000000
status                   2.657875
country_code            10.665885
state_code              38.992273
region                  10.665885
city                    12.371051
funding_rounds           0.000000
founded_at              22.015454
founded_month           22.161091
founded_quarter         22.161091
founded_year            22.161091
first_funding_at         0.000000
last_funding_at          0.000000
seed                     0.000000
venture                  0.000000
equity_crowdfunding      0.000000
undisclosed              0.000000
convertible_note         0.000000
debt_financing           0.000000
angel                    0.000000
grant                    0.000000
private_equity           0.000000
post_ipo_equity          0.000000
post_ipo_debt            0.000000
secondary_market         0.000000
product_crowdfunding     0.000000
round_A                  0.000000
round_B                  0.000000
round_C                  0.000000
round_D                  0.000000
round_E                  0.000000
round_F                  0.000000
round_G                  0.000000
round_H                  0.000000
dtype: float64

In [42]:
df[df.duplicated()]

Empty DataFrame
Columns: [permalink, name, homepage_url, category_list,  market ,  funding_total_usd , status, country_code, state_code, region, city, funding_rounds, founded_at, founded_month, founded_quarter, founded_year, first_funding_at, last_funding_at, seed, venture, equity_crowdfunding, undisclosed, convertible_note, debt_financing, angel, grant, private_equity, post_ipo_equity, post_ipo_debt, secondary_market, product_crowdfunding, round_A, round_B, round_C, round_D, round_E, round_F, round_G, round_H]
Index: []

In [43]:
df.columns

Index(['permalink', 'name', 'homepage_url', 'category_list', ' market ', ' funding_total_usd ',
       'status', 'country_code', 'state_code', 'region', 'city', 'funding_rounds', 'founded_at',
       'founded_month', 'founded_quarter', 'founded_year', 'first_funding_at', 'last_funding_at',
       'seed', 'venture', 'equity_crowdfunding', 'undisclosed', 'convertible_note',
       'debt_financing', 'angel', 'grant', 'private_equity', 'post_ipo_equity', 'post_ipo_debt',
       'secondary_market', 'product_crowdfunding', 'round_A', 'round_B', 'round_C', 'round_D',
       'round_E', 'round_F', 'round_G', 'round_H'],
      dtype='object')

In [44]:
df.columns=df.columns.str.strip()
df.columns

Index(['permalink', 'name', 'homepage_url', 'category_list', 'market', 'funding_total_usd',
       'status', 'country_code', 'state_code', 'region', 'city', 'funding_rounds', 'founded_at',
       'founded_month', 'founded_quarter', 'founded_year', 'first_funding_at', 'last_funding_at',
       'seed', 'venture', 'equity_crowdfunding', 'undisclosed', 'convertible_note',
       'debt_financing', 'angel', 'grant', 'private_equity', 'post_ipo_equity', 'post_ipo_debt',
       'secondary_market', 'product_crowdfunding', 'round_A', 'round_B', 'round_C', 'round_D',
       'round_E', 'round_F', 'round_G', 'round_H'],
      dtype='object')

In [45]:
df['funding_total_usd']=df['funding_total_usd'].str.strip().str.replace(',','').str.replace('-','0')
df['funding_total_usd']=df['funding_total_usd'].astype('int')

In [46]:
pd.set_option('display.max_columns', 50)
df.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,undisclosed,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,News,1750000,acquired,USA,NY,New York City,New York,1.0,2012-06-01,2012-06,2012-Q2,2012.0,2012-06-30,2012-06-30,1750000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,4000000,operating,USA,CA,Los Angeles,Los Angeles,2.0,NaN,NaN,NaN,NaN,2010-06-04,2010-09-23,0.0,4000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Publishing,40000,operating,EST,NaN,Tallinn,Tallinn,1.0,2012-10-26,2012-10,2012-Q4,2012.0,2012-08-09,2012-08-09,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Electronics,1500000,operating,GBR,NaN,London,London,1.0,2011-04-01,2011-04,2011-Q2,2011.0,2011-04-01,2011-04-01,1500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/organization/r-ranch-and-mine,-R- Ranch and Mine,NaN,|Tourism|Entertainment|Games|,Tourism,60000,operating,USA,TX,Dallas,Fort Worth,2.0,2014-01-01,2014-01,2014-Q1,2014.0,2014-08-17,2014-09-26,0.0,0.0,60000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [58]:
df[df['name'].isna()]

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,undisclosed,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
28221,/organization/tell-it-in,NaN,http://tellitin10.com,|Startups|,Startups,25000,closed,NaN,NaN,NaN,NaN,1.0,2011-10-01,2011-10,2011-Q4,2011.0,2012-03-01,2012-03-01,25000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [59]:
df['name'].fillna('Tell It in 10',inplace=True)

In [83]:
pd.set_option('display.max_columns', 50)

df[df[['category_list','market']].isna().any(axis=1)][['category_list','market']].shape

(3968, 2)

In [48]:
df.describe()

,funding_total_usd,funding_rounds,founded_year,seed,venture,equity_crowdfunding,undisclosed,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
count,4.943800e+04,49438.000000,38482.000000,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04
mean,1.316667e+07,1.696205,2007.359129,2.173215e+05,7.501051e+06,6.163322e+03,1.302213e+05,2.336410e+04,1.888157e+06,6.541898e+04,1.628453e+05,2.074286e+06,6.088736e+05,4.434360e+05,3.845592e+04,7.074227e+03,1.243955e+06,1.492891e+06,1.205356e+06,7.375261e+05,3.424682e+05,1.697692e+05,5.767067e+04,1.423197e+04
std,1.535540e+08,1.294213,7.579203,1.056985e+06,2.847112e+07,1.999048e+05,2.981404e+06,1.432046e+06,1.382046e+08,6.582908e+05,5.612088e+06,3.167231e+07,2.678348e+07,3.428169e+07,3.864461e+06,4.282166e+05,5.531974e+06,7.472704e+06,7.993592e+06,9.815218e+06,5.406915e+06,6.277905e+06,5.252312e+06,2.716865e+06
min,0.000000e+00,1.000000,1902.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,5.000000e+04,1.000000,2006.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.000000e+06,1.000000,2010.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,6.772162e+06,2.000000,2012.000000,2.500000e+04,5.000000e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,3.007950e+10,18.000000,2014.000000,1.300000e+08,2.351000e+09,2.500000e+07,2.924328e+08,3.000000e+08,3.007950e+10,6.359026e+07,7.505000e+08,3.500000e+09,4.700000e+09,5.800000e+09,6.806116e+08,7.200000e+07,3.190000e+08,5.420000e+08,4.900000e+08,1.200000e+09,4.000000e+08,1.060000e+09,1.000000e+09,6.000000e+08

In [49]:
df.describe(include='object')

,permalink,name,homepage_url,category_list,market,status,country_code,state_code,region,city,founded_at,founded_month,founded_quarter,first_funding_at,last_funding_at
count,49438,49437,45989,45477,45470,48124,44165,30161,44165,43322,38554,38482,38482,49438,49438
unique,49436,49350,45850,16675,753,3,115,61,1089,4188,3369,420,218,3914,3657
top,/organization/treasure-valley-urology-services,Roost,http://spaceport.io,|Software|,Software,operating,USA,CA,SF Bay Area,San Francisco,2012-01-01,2012-01,2012-Q1,2012-01-01,2013-01-01
freq,2,4,2,3650,4620,41829,28793,9917,6804,2615,2181,2327,2904,468,387

In [57]:
df=pd.read_csv('investments_VC.csv',encoding='latin')
df=df[~df.isna().all(axis=1)]
df.columns=df.columns.str.strip()
df['funding_total_usd']=df['funding_total_usd'].str.strip().str.replace(',','').str.replace('-','0')
df['funding_total_usd']=df['funding_total_usd'].astype('int')